sudo: required
services:
  - docker

before-install:
  - docker build -f Dockerfile.dev -t ashishumrani/docker-react  .

script:
  - docker run -e CI=true ashishumrani/docker-react npm run test -- --coverage


    